name: password
version: 1.0.0
description: A set of high-level APIs over PointyCastle to hash and verify passwords securely.
author: leocavalcante <lc@leocavalcante.com>
homepage: https://github.com/leocavalcante/password-dart
environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  pointycastle: ^1.0.0

dev_dependencies:
  test: ^1.5.1+1
