name: password
version: 0.1.0
description: A set of high-level APIs over PointyCastle and CryptoUtils to hash and verify passwords securely
author: leocavalcante <lc@leocavalcante.com>
homepage: https://github.com/leocavalcante/password-dart
environment:
  sdk: ">=2.0.0-dev <2.0.0"

dependencies:
  pointycastle: ^1.0.0-rc1
  cryptoutils: ^0.3.0

dev_dependencies:
  test: ^0.12.38
